services:
  exitslip.api:
    image: ${DOCKER_REGISTRY-}exitslipapi
    build:
      context: .
      dockerfile: ExitSlip.Api/Dockerfile

  forumfeedback.api:
    image: ${DOCKER_REGISTRY-}forumfeedbackapi
    build:
      context: .
      dockerfile: ForumFeedback.Api/Dockerfile


  login.api:
    image: ${DOCKER_REGISTRY-}loginapi
    build:
      context: .
      dockerfile: Login.Api/Dockerfile


  reverseproxy:
    image: ${DOCKER_REGISTRY-}reverseproxy
    build:
      context: .
      dockerfile: ReverseProxy/Dockerfile

  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
